package models

import (
	"testing"
	"time"

	"ETM/pkg/types"

	"github.com/google/uuid"
	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

// sqliteSchema creates all tables using SQLite-compatible DDL.
// We can't use GORM AutoMigrate here because some columns carry
// PostgreSQL-specific DEFAULT expressions (gen_random_uuid()) that
// SQLite rejects. The BeforeCreate hooks handle UUID generation in Go,
// so no DB-level default is needed for tests.
var sqliteSchema = []string{
	`CREATE TABLE IF NOT EXISTS users (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		uuid TEXT, username TEXT, password TEXT, gid INTEGER,
		is_admin TEXT, telegram TEXT, browser TEXT, email TEXT,
		oidc_subject TEXT, oidc_provider TEXT
	)`,
	`CREATE TABLE IF NOT EXISTS groups (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		name TEXT, owner_id INTEGER
	)`,
	`CREATE TABLE IF NOT EXISTS user_groups (
		user_id INTEGER NOT NULL, group_id INTEGER NOT NULL, role TEXT,
		PRIMARY KEY (user_id, group_id)
	)`,
	`CREATE TABLE IF NOT EXISTS categories (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		name TEXT, color TEXT, user_id INTEGER, active INTEGER
	)`,
	`CREATE TABLE IF NOT EXISTS category_groups (
		category_id INTEGER NOT NULL, group_id INTEGER NOT NULL,
		PRIMARY KEY (category_id, group_id)
	)`,
	`CREATE TABLE IF NOT EXISTS tasks (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		name TEXT, comment TEXT, is_completed INTEGER, is_back_log INTEGER,
		category_id INTEGER, priority INTEGER, urgency INTEGER,
		due_date DATETIME, user_id INTEGER
	)`,
	`CREATE TABLE IF NOT EXISTS keys (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		pubkey TEXT, privkey TEXT
	)`,
	`CREATE TABLE IF NOT EXISTS devices (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		uuid TEXT, user_id INTEGER, device_id TEXT, device_name TEXT,
		trusted INTEGER, last_used_at DATETIME
	)`,
	`CREATE TABLE IF NOT EXISTS tokens (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		created_at DATETIME, updated_at DATETIME, deleted_at DATETIME,
		uuid TEXT, user_id INTEGER, device_id TEXT,
		refresh_token TEXT, country TEXT
	)`,
}

// newTestDB returns a DB backed by an in-memory SQLite database.
// Tests are isolated because each call gets a fresh DB.
func newTestDB(t *testing.T) *DB {
	t.Helper()
	gdb, err := gorm.Open(sqlite.Open(":memory:"), &gorm.Config{})
	if err != nil {
		t.Fatalf("open test db: %v", err)
	}
	for _, sql := range sqliteSchema {
		if err := gdb.Exec(sql).Error; err != nil {
			t.Fatalf("create table: %v\nSQL: %s", err, sql)
		}
	}
	return &DB{DB: *gdb}
}

func makeUser(t *testing.T, db *DB, username string) Users {
	t.Helper()
	user := Users{UUID: uuid.New(), Username: username, Email: username + "@test.com", Password: "hash"}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("create user: %v", err)
	}
	return user
}

func makeCategory(t *testing.T, db *DB, owner Users) Category {
	t.Helper()
	cat, err := db.CreateCategory(types.CategoryBody{Name: "Work", Color: "#fff", Active: true}, owner)
	if err != nil {
		t.Fatalf("create category: %v", err)
	}
	return cat
}

// ── Users ─────────────────────────────────────────────────────────────────────

func TestCreateUser_GetByUUID(t *testing.T) {
	db := newTestDB(t)
	id := uuid.New()
	user := Users{UUID: id, Username: "alice", Email: "alice@test.com", Password: "hash"}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("create: %v", err)
	}
	got, err := db.GetUserByUUID(id)
	if err != nil {
		t.Fatalf("get by uuid: %v", err)
	}
	if got.Username != "alice" {
		t.Errorf("username: got %q, want %q", got.Username, "alice")
	}
}

func TestGetUserByUUID_NotFound(t *testing.T) {
	db := newTestDB(t)
	_, err := db.GetUserByUUID(uuid.New())
	if err == nil {
		t.Error("expected error for non-existent uuid")
	}
}

func TestBeforeCreate_UUIDAutoGenerated(t *testing.T) {
	db := newTestDB(t)
	// Don't set UUID — BeforeCreate hook should fill it.
	user := Users{Username: "bob", Email: "bob@test.com", Password: "hash"}
	if err := db.Create(&user).Error; err != nil {
		t.Fatalf("create: %v", err)
	}
	if user.UUID == (uuid.UUID{}) {
		t.Error("expected UUID to be auto-generated by BeforeCreate hook")
	}
	if user.ID == 0 {
		t.Error("expected non-zero primary key")
	}
}

func TestCreateUser_ViaHelper(t *testing.T) {
	db := newTestDB(t)
	body := types.UserBody{Username: "carol", Email: "carol@test.com", Password: "hashed"}
	if err := db.CreateUser(body); err != nil {
		t.Fatalf("create user: %v", err)
	}
	var u Users
	if err := db.Where("username = ?", "carol").First(&u).Error; err != nil {
		t.Errorf("user not found after create: %v", err)
	}
}

// ── Categories ────────────────────────────────────────────────────────────────

func TestCreateCategory(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")

	cat, err := db.CreateCategory(types.CategoryBody{Name: "Personal", Color: "#f00", Active: true}, owner)
	if err != nil {
		t.Fatalf("create category: %v", err)
	}
	if cat.ID == 0 {
		t.Error("expected non-zero category ID")
	}
	if cat.Name != "Personal" {
		t.Errorf("name: got %q, want %q", cat.Name, "Personal")
	}
}

func TestGetCategories_OwnedOnly(t *testing.T) {
	db := newTestDB(t)
	alice := makeUser(t, db, "alice")
	bob := makeUser(t, db, "bob")
	makeCategory(t, db, alice)
	makeCategory(t, db, alice)
	makeCategory(t, db, bob)

	cats, err := db.GetCategories(alice.ID)
	if err != nil {
		t.Fatalf("get categories: %v", err)
	}
	if len(cats) != 2 {
		t.Errorf("got %d categories, want 2", len(cats))
	}
}

func TestCanUserViewCategory_Owner(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	cat := makeCategory(t, db, owner)

	if !db.CanUserViewCategory(owner.ID, cat.ID) {
		t.Error("owner should be able to view their own category")
	}
}

func TestCanUserViewCategory_OtherUser(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	other := makeUser(t, db, "other")
	cat := makeCategory(t, db, owner)

	if db.CanUserViewCategory(other.ID, cat.ID) {
		t.Error("unrelated user should not be able to view category")
	}
}

func TestCanUserEditCategory_Owner(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	cat := makeCategory(t, db, owner)

	if !db.CanUserEditCategory(owner.ID, cat.ID) {
		t.Error("owner should be able to edit their own category")
	}
}

// ── Tasks ─────────────────────────────────────────────────────────────────────

func TestCreateTask_GetTask(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	cat := makeCategory(t, db, owner)

	task := &Tasks{
		Name:       "Fix bug",
		Comment:    "asap",
		CategoryID: cat.ID,
		UserID:     owner.ID,
		DueDate:    time.Now().Add(24 * time.Hour),
		IsBackLog:  true,
	}
	if err := db.CreateTask(task); err != nil {
		t.Fatalf("create task: %v", err)
	}
	if task.ID == 0 {
		t.Fatal("expected non-zero task ID")
	}

	got, err := db.GetTask(int(task.ID))
	if err != nil {
		t.Fatalf("get task: %v", err)
	}
	if got.Name != "Fix bug" {
		t.Errorf("name: got %q, want %q", got.Name, "Fix bug")
	}
}

func TestUpdateTask(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	cat := makeCategory(t, db, owner)

	task := &Tasks{Name: "Original", CategoryID: cat.ID, UserID: owner.ID, DueDate: time.Now().Add(time.Hour)}
	_ = db.CreateTask(task)

	task.Name = "Updated"
	task.Priority = true
	if err := db.UpdateTask(task); err != nil {
		t.Fatalf("update task: %v", err)
	}

	got, _ := db.GetTask(int(task.ID))
	if got.Name != "Updated" {
		t.Errorf("name: got %q, want %q", got.Name, "Updated")
	}
	if !got.Priority {
		t.Error("expected Priority to be true after update")
	}
}

func TestDeleteTask(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	cat := makeCategory(t, db, owner)

	task := &Tasks{Name: "Temp", CategoryID: cat.ID, UserID: owner.ID, DueDate: time.Now()}
	_ = db.CreateTask(task)

	if err := db.DeleteTask(task.ID); err != nil {
		t.Fatalf("delete task: %v", err)
	}
	_, err := db.GetTask(int(task.ID))
	if err == nil {
		t.Error("expected error when fetching deleted task")
	}
}

func TestGetTasksByCategory(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	cat := makeCategory(t, db, owner)

	for i := 0; i < 3; i++ {
		_ = db.CreateTask(&Tasks{Name: "t", CategoryID: cat.ID, UserID: owner.ID, DueDate: time.Now()})
	}

	tasks, err := db.GetTasksByCategory(cat.ID)
	if err != nil {
		t.Fatalf("get tasks by category: %v", err)
	}
	if len(tasks) != 3 {
		t.Errorf("got %d tasks, want 3", len(tasks))
	}
}

// ── Groups ────────────────────────────────────────────────────────────────────

func TestCreateGroup_OwnerIsAutoAdded(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")

	group, err := db.CreateGroup("Team Alpha", owner.ID)
	if err != nil {
		t.Fatalf("create group: %v", err)
	}
	if !db.IsGroupOwner(group.ID, owner.ID) {
		t.Error("expected creator to be group owner")
	}
	if !db.IsGroupMember(group.ID, owner.ID) {
		t.Error("expected creator to be group member")
	}
}

func TestAddGroupMember_InvalidRole(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	member := makeUser(t, db, "member")

	group, _ := db.CreateGroup("Team", owner.ID)
	err := db.AddGroupMember(group.ID, member.ID, "superadmin")
	if err == nil {
		t.Error("expected error for invalid role")
	}
}

func TestAddGroupMember_ValidRole(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	member := makeUser(t, db, "member")

	group, _ := db.CreateGroup("Team", owner.ID)
	if err := db.AddGroupMember(group.ID, member.ID, "editor"); err != nil {
		t.Fatalf("add member: %v", err)
	}
	if !db.IsGroupMember(group.ID, member.ID) {
		t.Error("expected user to be group member after AddGroupMember")
	}
}

func TestCanUserEditCategory_SharedEditorCanEdit(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	editor := makeUser(t, db, "editor")

	cat := makeCategory(t, db, owner)
	group, _ := db.CreateGroup("Collab", owner.ID)
	_ = db.AddGroupMember(group.ID, editor.ID, "editor")
	_ = db.ShareCategoryWithGroup(cat.ID, group.ID)

	if !db.CanUserEditCategory(editor.ID, cat.ID) {
		t.Error("editor group member should be able to edit shared category")
	}
}

func TestCanUserEditCategory_ViewerCannotEdit(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	viewer := makeUser(t, db, "viewer")

	cat := makeCategory(t, db, owner)
	group, _ := db.CreateGroup("Readers", owner.ID)
	_ = db.AddGroupMember(group.ID, viewer.ID, "viewer")
	_ = db.ShareCategoryWithGroup(cat.ID, group.ID)

	if db.CanUserEditCategory(viewer.ID, cat.ID) {
		t.Error("viewer group member should not be able to edit category")
	}
}

// ── Tokens ────────────────────────────────────────────────────────────────────

func TestGetTokenByID_NotFound(t *testing.T) {
	db := newTestDB(t)
	_, err := db.GetTokenByID(9999)
	if err == nil {
		t.Error("expected error for non-existent token ID")
	}
}

func TestDeleteToken_OwnershipCheck(t *testing.T) {
	db := newTestDB(t)
	owner := makeUser(t, db, "owner")
	other := makeUser(t, db, "other")

	tok := &Tokens{UserID: owner.ID, RefreshToken: "abc"}
	if err := db.CreateToken(tok); err != nil {
		t.Fatalf("create token: %v", err)
	}

	// Simulate ownership check: fetch and compare
	fetched, err := db.GetTokenByID(tok.ID)
	if err != nil {
		t.Fatalf("get token: %v", err)
	}
	if fetched.UserID == other.ID {
		t.Error("token should belong to owner, not other")
	}
}
