/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Categories: typeof import('./components/categories.vue')['default']
    Categorycomponent: typeof import('./components/categorycomponent.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUpForm: typeof import('./components/SignUpForm.vue')['default']
    Taskcomponent: typeof import('./components/taskcomponent.vue')['default']
    Tasklist: typeof import('./components/tasklist.vue')['default']
  }
}
